{% set version = "1.3.0" %}

package:
  name: libpyvinyl
  version: {{ version }}

source:
  url: https://github.com/PaNOSC-ViNYL/libpyvinyl/archive/v{{ version }}.tar.gz
  sha256: 1e83f89b3b702d6b527bba6a2efd64b4c76cad23ad8a8c305ad356381bcd4e93

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - pint
    - dill <=0.3.5.1
    - scipy
    - jsons
    - h5py
    - json_tricks

test:
  imports:
    - libpyvinyl
  commands:
    - pip check
    - pytest .
  source_files:
    - ./
  requires:
    - pytest
    - pip
    - python {{ python_min }}

about:
  home: https://libpyvinyl.readthedocs.io/en/latest/
  summary: Python API for the Virtual Neutron and x-raY Laboratory
  description: |
    Simulations provide invaluable insights to plan (before) and understand (after)
    experiments at neutron and X-ray facilities. A wide set of libraries and
    programs is already available to simulate neutron and X-ray beams, propagate
    them through the beamlines, interact with the sample and get data acquired by
    detectors.

    The aim of libpyvinyl is to provide a high level neutron and X-ray simulation
    API. With this harmonized user interface we achieve seamless interoperability of
    individual simulations thereby facilitating the concatenation of simulation
    steps into a simulation pipeline. The vast differences with respect to parameter
    names, unit conventions, configuration syntax, i.e. the user interface, is,
    hence, overcome creating a libpyvinyl compliant API for each simulation
    software.
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: LICENSE
  doc_url: https://libpyvinyl.readthedocs.io/en/latest/
  dev_url: https://github.com/PaNOSC-ViNYL/libpyvinyl

extra:
  recipe-maintainers:
    #TODO: Add other libpyvinyl developers as appropriate.
    - mads-bertelsen
    - tkittel
